# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

---
-
    name: Kreta
    hosts: prod
    roles:
        - carlosbuenosvinos.ansistrano-deploy
    vars_files:
        - vars/all.yml
        - vars/prod.yml
