# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

---
-
    name: Kreta
    hosts: webservers
    roles:
        - carlosbuenosvinos.ansistrano-deploy
    vars:
        permission_owner: root
        permission_group: root
        permission_mode: "0755"
        ansistrano_deploy_from: "../"
        ansistrano_deploy_to: "/var/www/kreta.io"
        ansistrano_keep_releases: 2
        ansistrano_deploy_via: "git"            # Also it can be copy, rsync
        ansistrano_git_repo: git@github.com:kreta/Kreta.git
        ansistrano_git_branch: "master"

        ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/config/after-update-code.yml"

        ansistrano_shared_folders:
            - IdentityAccess/var/jwt
            - IdentityAccess/var/logs
            - IdentityAccess/var/sessions
            - IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Ui/Uploads
            - TaskManager/var/logs
            - TaskManager/var/sessions

        ansistrano_shared_files:
            - IdentityAccess/parameters.yml
            - TaskManager/parameters.yml

        php_path: /usr/bin/php70
        composer_path: "{{ ansistrano_deploy_to }}/composer.phar"
