# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.event_listener.authentication:
        class: Kreta\TaskManager\Infrastructure\Symfony\EventListener\AuthenticationListener
        arguments:
            - "@httplug.message_factory"
            - "@httplug.client"
            - "@security.token_storage"
            - "%identity_access_composite_ui_scheme%://%task_manager_identity_access_host%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
