# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Notification\Model\Notification:
    exclusion_policy: ALL
    relations:
        -
            rel: notifications
            href:
                route: get_notifications
                absolute: 0
            exclusion:
                groups: [notificationList, notification]
        -
            rel: projects
            href:
                route: get_projects
                absolute: 0
            exclusion:
                groups: [notificationList, notification]
    properties:
        id:
            expose: true
            groups: [notificationList, notification]
        description:
            expose: true
            groups: [notificationList, notification]
        date:
            expose: true
            groups: [notificationList, notification]
        read:
            expose: true
            groups: [notificationList, notification]
        resourceUrl:
            expose: true
            groups: [notificationList, notification]
        title:
            expose: true
            groups: [notificationList, notification]
        type:
            expose: true
            groups: [notificationList, notification]
        webUrl:
            expose: true
            groups: [notificationList, notification]
