# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
    kreta_core.factory.comment:
        class: %kreta_core.factory_comment.class%
        arguments: [%kreta_core.comment.class%]
    kreta_core.factory.issue:
        class: %kreta_core.factory_issue.class%
        arguments: [%kreta_core.issue.class%]
    kreta_core.factory.label:
        class: %kreta_core.factory_label.class%
        arguments: [%kreta_core.label.class%]
    kreta_core.factory.media:
        class: %kreta_core.factory_media.class%
        arguments: [%kreta_core.media.class%]
    kreta_core.factory.project:
        class: %kreta_core.factory_project.class%
        arguments: [%kreta_core.project.class%, @kreta_core.factory.participant]
    kreta_core.factory.participant:
        class: %kreta_core.factory_participant.class%
        arguments: [%kreta_core.participant.class%]
    kreta_core.factory.resolution:
        class: %kreta_core.factory_resolution.class%
        arguments: [%kreta_core.resolution.class%]
    kreta_core.factory.status:
        class: %kreta_core.factory_status.class%
        arguments: [%kreta_core.status.class%]
    kreta_core.factory.user:
        class: %kreta_core.factory_user.class%
        arguments: [%kreta_core.user.class%]
