# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_core.form_handler.handler:
        class: %kreta_core.form_handler.handler.class%
        abstract: true
        arguments:
            - @form.factory
            - @doctrine.orm.entity_manager
