# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_core.event_listener.json_exception:
        class: %kreta_core.event_listener.json_exception.class%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }

    kreta_core.event_listener.resource_if_allowed_annotation:
        class: %kreta_core.event_listener.resource_if_allowed_annotation.class%
        abstract: true
        arguments:
            - '@annotations.reader'
            - '@security.authorization_checker'

    kreta_core.event_listener.role_annotation:
        class: %kreta_core.event_listener.role_annotation.class%
        arguments:
            - '@annotations.reader'
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onRoleAnnotationMethod }
