# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
#### SECURITY ####
    kreta_user_provider:
        class: %kreta_core.security_class_userProvider%
        arguments: [@fos_user.user_manager, {bitbucket: bitbucketId, github: githubId}]

    kreta_issue_voter:
        class: %kreta_core.security_class_issueVoter%
        public: false
        tags:
           - { name: security.voter }

    kreta_project_voter:
        class: %kreta_core.security_class_projectVoter%
        public: false
        tags:
           - { name: security.voter }

#### STATE MACHINE ####
    kreta_core.issue_state_machine:
        class: %kreta_core.state_machine_class_issue%

#### UPLOADER ####
    kreta_core.image_users_uploader:
        class: %kreta_core.uploader_class_mediaUploader%
        arguments: [@kreta_core.image_users_uploader_filesystem]
    kreta_core.image_projects_uploader:
        class: %kreta_core.uploader_class_mediaUploader%
        arguments: [@kreta_core.image_projects_uploader_filesystem]

    kreta_core.image_users_uploader_filesystem:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments: [%users.image.uploader.filesystem%]
    kreta_core.image_projects_uploader_filesystem:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments: [%projects.image.uploader.filesystem%]
