# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Core\Model\Project:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [shortName]
            message: 'Short name is already in use'
    properties:
        name:
            - NotBlank: ~
        shortName:
            - NotBlank: ~
            - Length:
                min: 4
                max: 4
                minMessage: 'Short name must be at least {{ limit }} characters long'
                maxMessage: 'Short name cannot be longer than {{ limit }} characters long'
Kreta\Component\Core\Model\Status:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, project]
            message: 'This status is already exist in this project'
    properties:
        color:
            - NotBlank: ~
        name:
            - NotBlank: ~
        type:
            - NotBlank: ~
Kreta\Component\Core\Model\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title, project]
            message: 'An issue with identical title is already exist in this project'
    properties:
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        assignee:
            - NotBlank: ~
Kreta\Component\Core\Model\Status:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title, project]
            message: 'An issue with identical title is already exist in this project'
    properties:
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        assignee:
            - NotBlank: ~
