# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Workflow\Model\Workflow:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_workflow
                parameters:
                    workflowId: expr(object.getId())
                absolute: 0
            exclusion:
                groups: [workflowList, workflow]
        -
            rel: workflows
            href:
                route: get_workflows
                absolute: 0
            exclusion:
                groups: [workflowList, workflow]
    properties:
        createdAt:
            expose: true
            groups: [workflowList, workflow]
        name:
            expose: true
            groups: [workflowList, workflow, projectList, project, projectPrivate]
        statuses:
            expose: true
            groups: [workflowList, workflow, project, projectPrivate]
        statusTransitions:
            expose: true
            groups: [workflowList, workflow, project, projectPrivate]
