# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Workflow\Model\Status:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_workflow_status
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                    statusId: expr(object.getId())
                absolute: 0
            exclusion:
                groups: [workflowList, workflow, statusList, status]
        -
            rel: statuses
            href:
                route: get_workflow_statuses
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: 0
            exclusion:
                groups: [workflowList, workflow, statusList, status]
        -
            rel: workflow
            href:
                route: get_workflow
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: 0
            exclusion:
                groups: [statusList, status]
    properties:
        id:
            expose: true
            groups: [workflowList, workflow, projectList, project, projectPrivate, issueList, issue, statusList, status, transitionList, transition]
        color:
            expose: true
            groups: [workflowList, workflow, projectList, project, projectPrivate, issueList, issue, statusList, status, transitionList, transition]
        name:
            expose: true
            groups: [workflowList, workflow, projectList, project, projectPrivate, issueList, issue, statusList, status, transitionList, transition]
        type:
            expose: true
            groups: [workflowList, workflow, projectList, project, projectPrivate, issueList, issue, statusList, status, transitionList, transition]
        transitions:
            expose: true
            groups: []
        workflow:
            expose: true
            groups: []
