# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.query_handler.count_organizations:
        class: Kreta\TaskManager\Application\Query\Organization\CountOrganizationsHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.specification_factory.organization"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\CountOrganizationsQuery

    kreta.task_manager.query_handler.filter_organizations:
        class: Kreta\TaskManager\Application\Query\Organization\FilterOrganizationsHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.specification_factory.organization"
            - "@kreta.task_manager.data_transformer.organization_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\FilterOrganizationsQuery

    kreta.task_manager.query_handler.organization_of_id:
        class: Kreta\TaskManager\Application\Query\Organization\OrganizationOfIdHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.data_transformer.organization_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\OrganizationOfIdQuery

    kreta.task_manager.query_handler.organization_of_slug:
        class: Kreta\TaskManager\Application\Query\Organization\OrganizationOfSlugHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.data_transformer.organization_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\OrganizationOfSlugQuery

    kreta.task_manager.query_handler.organization_member_of_id:
        class: Kreta\TaskManager\Application\Query\Organization\OrganizationMemberOfIdHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.data_transformer.member_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\OrganizationMemberOfIdQuery

    kreta.task_manager.query_handler.owner_of_id:
        class: Kreta\TaskManager\Application\Query\Organization\OwnerOfIdHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.data_transformer.member_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\OwnerOfIdQuery
