# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

addons:
    hosts:
        - kreta.test

language: php

php:
    - 7.1

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - composer self-update
    - sh etc/bash/install.sh

script:
    - sh etc/bash/tests.sh

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
