# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION}

    - app/console doctrine:database:create --env=test
    - app/console doctrine:schema:create --env=test

script:
    - bin/phpspec run -fpretty

    - bin/behat --stop-on-failure --suite=issue
    - bin/behat --stop-on-failure --suite=project

after_script:
    - bin/coveralls -v

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    allow_failures:
        - php: hhvm
        - env: SYMFONY_VERSION=dev-master
