# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

addons:
    ssh_known_hosts:
        - 137.74.161.60

language: php

php:
    - 7.1

env:
    - COMPOSER_OPTIONS="--no-interaction --prefer-source"

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update

    - pip install --user -U pip
    - pip install --user --upgrade pip
    - pip install --user --upgrade ansible
    - printf '[defaults]\nroles_path=../' >ansible.cfg
    - ansible --version
    - ansible-galaxy install carlosbuenosvinos.ansistrano-deploy --force
    - ln -s `pwd` ../kreta.Kreta

install:
    - nvm install 7
    - nvm use 7
    - npm install -g yarn

    - cd SharedKernel
    - composer install
    - cd -

    - cd IdentityAccess
    - composer install
    - sh etc/bash/generate_ssh_keys.sh
    - cd -

    - cd TaskManager
    - composer install
    - cd -

    - cd CompositeUi
    - yarn install
    - sh etc/bash/update_graph_schema.sh
    - cd -

    - sh etc/bash/install_test_env.sh

cache:
    yarn: true
    directories:
        - node_modules
        - $HOME/.composer/cache/files
        - $HOME/.php-cs-fixer
        - $HOME/virtualenv

script:
    - cd SharedKernel
    - vendor/bin/phpspec run -fdot
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.php_cs --diff --dry-run -v
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.phpspec_cs --diff --dry-run -v
    - cd -

    - cd IdentityAccess
    - vendor/bin/phpspec run -fdot
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.php_cs --diff --dry-run -v
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.phpspec_cs --diff --dry-run -v
    - etc/bin/symfony-console lint:yaml src/Kreta/IdentityAccess/Infrastructure
## The following check is commented because Travis CI throws an error:
## "An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.."
#    - etc/bin/symfony-console security:check
    - cd -

    - cd TaskManager
    - vendor/bin/phpspec run -fdot
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.php_cs --diff --dry-run -v
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.phpspec_cs --diff --dry-run -v
    - etc/bin/symfony-console lint:yaml src/Kreta/TaskManager/Infrastructure
## The following check is commented because Travis CI throws an error:
## "An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.."
#    - etc/bin/symfony-console security:check
    - cd -

    - cd CompositeUi
    - yarn test
    - cd -

deploy:
    skip_cleanup: true
    provider: script
    script: .travis/deploy.sh
    on:
        branch: master
