# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 7.1

env:
    - COMPOSER_OPTIONS="--no-interaction --prefer-source"

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update

install:
    - nvm install 7
    - nvm use 7
    - npm install -g yarn

    - cd SharedKernel
    - composer install -o
    - cd -

    - cd IdentityAccess
    - composer install -o
    - sh etc/bash/generate_ssh_keys.sh
    - cd -

    - cd TaskManager
    - composer install -o
    - cd -

    - cd CompositeUi
    - yarn install
    - sh etc/bash/update_graph_schema.sh
    - cd -

    - sh etc/bash/install_test_env.sh

cache:
    yarn: true
    directories:
        - node_modules
        - $COMPOSER_CACHE_DIR
        - $HOME/.composer/cache/files
        - $HOME/.php-cs-fixer

matrix:
    fast_finish: true
    include:
        php: 7.1

script:
    - cd SharedKernel
    - vendor/bin/phpspec run -fdot
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.php_cs --diff --dry-run -v
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.phpspec_cs --diff --dry-run -v
    - cd -

    - cd IdentityAccess
    - vendor/bin/phpspec run -fdot
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.php_cs --diff --dry-run -v
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.phpspec_cs --diff --dry-run -v
    - etc/bin/symfony-console lint:yaml src/Kreta/IdentityAccess/Infrastructure
## The following check is commented because Travis CI throws an error:
## "An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.."
#    - etc/bin/symfony-console security:check
    - cd -

    - cd TaskManager
    - vendor/bin/phpspec run -fdot
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.php_cs --diff --dry-run -v
    - vendor/bin/php-cs-fixer fix --config=etc/phpcs/.phpspec_cs --diff --dry-run -v
    - etc/bin/symfony-console lint:yaml src/Kreta/TaskManager/Infrastructure
## The following check is commented because Travis CI throws an error:
## "An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.."
#    - etc/bin/symfony-console security:check
    - cd -

    - cd CompositeUi
    - yarn test
