# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - nvm install 4.2.1
    - nvm use 4.2.1
    - composer update --no-interaction ${COMPOSER_OPTIONS}
    - cd Bundle/WebBundle
    - npm install
    - cd -

script:
    - cd Bundle/WebBundle
    - node_modules/.bin/jest --verbose --coverage
    - cd -
    - vendor/bin/phpspec run -fpretty

after_script:
    - vendor/bin/coveralls -v

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm
