# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

addons:
    hosts:
        - kreta.test

language: php

php:
    - 7.0

env:
    - COMPOSER_OPTIONS="--prefer-source"

install:
    - composer self-update
    - composer install --no-interaction ${COMPOSER_OPTIONS}

before_script:
    - IdentityAccess/etc/bash/generate_ssh_keys.sh
    - IdentityAccess/etc/bash/load_database.sh
    - IdentityAccess/etc/bash/server_start.sh

    - TaskManager/etc/bash/load_database.sh
    - TaskManager/etc/bash/server_start.sh

script:
    - vendor/bin/phpspec run

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
