# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

kreta_api_profile:
    type: rest
    resource: Kreta\Bundle\UserBundle\Controller\ProfileController

kreta_api_invitation:
    type: rest
    resource: Kreta\Bundle\UserBundle\Controller\InvitationController

kreta_api_user:
    type: rest
    resource: Kreta\Bundle\UserBundle\Controller\UserController
