# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_workflow.factory.status:
        class: %kreta_workflow.factory_status.class%
        arguments: [%kreta_workflow.status.class%]
    kreta_workflow.factory.status_transition:
        class: %kreta_workflow.factory_status_transition.class%
        arguments: [%kreta_workflow.status_transition.class%]
    kreta_workflow.factory.workflow:
        class: %kreta_workflow.factory_workflow.class%
        arguments: [%kreta_workflow.workflow.class%]
