# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### HANDLERS ####
    kreta_workflow.form_handler.status:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Workflow\Form\Type\StatusType
    kreta_workflow.form_handler.status_transition:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Workflow\Form\Type\StatusTransitionType
    kreta_workflow.form_handler.workflow:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Workflow\Form\Type\WorkflowType

#### TYPES ####
    kreta_workflow.form_type.status:
        class: %kreta_workflow.form_type.status.class%
        arguments:
            - %kreta_workflow.status.class%
            - @kreta_workflow.factory.status
            - @security.token_storage
        tags:
            - { name: form.type }
    kreta_workflow.form_type.status_transition:
        class: %kreta_workflow.form_type.status_transition.class%
        arguments:
            - %kreta_workflow.status_transition.class%
            - @kreta_workflow.factory.status_transition
            - @security.token_storage
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type }
    kreta_workflow.form_type.workflow:
        class: %kreta_workflow.form_type.workflow.class%
        arguments:
            - %kreta_workflow.workflow.class%
            - @kreta_workflow.factory.workflow
            - @security.token_storage
        tags:
            - { name: form.type }
