# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_workflow.workflow.class: Kreta\Component\Workflow\Model\Workflow
    kreta_workflow.status.class: Kreta\Component\Workflow\Model\Status
    kreta_workflow.status_transition.class: Kreta\Component\Workflow\Model\StatusTransition

    kreta_workflow.factory_status.class: Kreta\Component\Workflow\Factory\StatusFactory
    kreta_workflow.factory_status_transition.class: Kreta\Component\Workflow\Factory\StatusTransitionFactory
    kreta_workflow.factory_workflow.class: Kreta\Component\Workflow\Factory\WorkflowFactory

    kreta_workflow.repository_workflow.class: Kreta\Component\Workflow\Repository\WorkflowRepository
    kreta_workflow.repository_status.class: Kreta\Component\Workflow\Repository\StatusRepository
    kreta_workflow.repository_status_transition.class: Kreta\Component\Workflow\Repository\StatusTransitionRepository

    kreta_workflow.form_type.status.class: Kreta\Component\Workflow\Form\Type\StatusType
    kreta_workflow.form_type.status_transition.class: Kreta\Component\Workflow\Form\Type\StatusTransitionType
    kreta_workflow.form_type.workflow.class: Kreta\Component\Workflow\Form\Type\WorkflowType

    kreta_workflow.security_workflow_voter.class: Kreta\Bundle\WorkflowBundle\Security\Authorization\Voter\WorkflowVoter
