# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_workflow.repository.workflow:
        class: %kreta_workflow.repository_workflow.class%
        factory:
            - @doctrine.orm.entity_manager
            - getRepository
        arguments:
            - %kreta_workflow.workflow.class%
    kreta_workflow.repository.status:
        class: %kreta_workflow.repository_status.class%
        factory:
            - @doctrine.orm.entity_manager
            - getRepository
        arguments:
            - %kreta_workflow.status.class%
    kreta_workflow.repository.status_transition:
        class: %kreta_workflow.repository_status_transition.class%
        factory:
            - @doctrine.orm.entity_manager
            - getRepository
        arguments:
            - %kreta_workflow.status_transition.class%
