# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

kreta_api_workflow:
    type: rest
    resource: Kreta\Bundle\WorkflowBundle\Controller\WorkflowController

kreta_api_status:
    type: rest
    parent: kreta_api_workflow
    resource: Kreta\Bundle\WorkflowBundle\Controller\StatusController

kreta_api_status_transitions:
    type: rest
    parent: kreta_api_workflow
    resource: Kreta\Bundle\WorkflowBundle\Controller\StatusTransitionController
