# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Workflow\Model\Status:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, workflow]
            message: 'A status with identical name is already exists in this workflow'
    properties:
        color:
            - NotBlank: ~
        name:
            - NotBlank: ~
        type:
            - NotBlank: ~

Kreta\Component\Workflow\Model\StatusTransition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, workflow]
            message: 'A transition with identical name is already exists in this workflow'
    properties:
        initialStates:
            - Count:
                min: 1
                minMessage: 'The transition must have at least one initial status'
        name:
            - NotBlank: ~
        state:
            - NotBlank: ~
    getters:
        validState:
            - IsTrue:
                message: 'The state cannot be an initial state too'

Kreta\Component\Workflow\Model\Workflow:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'A workflow with identical name is already exists'
    properties:
        name:
            - NotBlank: ~
