# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    rabbitmq:
        image: rabbitmq:3.6.5-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    task_manager:
        build: php7-fpm
        ports:
            - 9000:9000
        environment:
            TASK_MANAGER_DOMAIN: ${TASK_MANAGER_DOMAIN}
        links:
            - db
        volumes:
            - ../../TaskManager:/var/www/${TASK_MANAGER_DOMAIN}
            - ./data/logs/task_manager:/var/www/${TASK_MANAGER_ENV}/var/logs

    identity_access:
        build: php7-fpm
        ports:
            - 9001:9001
        environment:
            IDENTITY_ACCESS_DOMAIN: ${IDENTITY_ACCESS_DOMAIN}
        links:
            - db
        volumes:
            - ../../IdentityAccess:/var/www/${IDENTITY_ACCESS_DOMAIN}
            - ./data/logs/identity_access:/var/www/${IDENTITY_ACCESS_DOMAIN}/var/logs

    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - task_manager
            - identity_access
        volumes_from:
            - task_manager
            - identity_access
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
