# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Issue\Model\Issue:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_issue
                parameters:
                    issueId: expr(object.getId())
                absolute: true
            exclusion:
                groups: [issueList, issue]
        -
            rel: project
            href:
                route: get_project
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: true
            exclusion:
                groups: [issueList, issue]
        -
            rel: issues
            href:
                route: get_issues
                absolute: true
            exclusion:
                groups: [issueList, issue]
    properties:
        assignee:
            expose: true
            groups: [issueList, issue]
        children:
            expose: true
            groups: [issueList, issue]
        createdAt:
            expose: true
            groups: [issueList, issue]
        description:
            expose: true
            groups: [issueList, issue]
        labels:
            expose: true
            groups: [issueList, issue]
        numericId:
            expose: true
            groups: [issueList, issue]
        parent:
            expose: true
            groups: [issueList, issue]
        priority:
            expose: true
            groups: [issueList, issue]
        project:
        project:
            expose: true
            groups: []
        resolution:
            expose: true
            groups: [issueList, issue]
        reporter:
            expose: true
            groups: [issueList, issue]
        status:
            expose: true
            groups: [issueList, issue]
        title:
            expose: true
            groups: [issueList, issue]
