# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Project\Model\Label:
    exclusion_policy: ALL
    relations:
        -
            rel: labels
            href:
                route: get_projects_labels
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: 0
            exclusion:
                groups: [labelList, label]
        -
            rel: project
            href:
                route: get_project
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: 0
            exclusion:
                groups: [labelList, label]
    properties:
        name:
            expose: true
            groups:
                - projectList
                - project
                - projectPrivate
                - issueList
                - issue
                - labelList
                - label
