# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Project\Model\Participant:
    exclusion_policy: ALL
    relations:
        -
            rel: participants
            href:
                route: get_projects_participants
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: 0
            exclusion:
                groups: [participantList, participant]
        -
            rel: project
            href:
                route: get_project
                parameters:
                    projectId: expr(object.getProject().getId())
                absolute: 0
            exclusion:
                groups: [participantList, participant]
        -
            rel: projects
            href:
                route: get_projects
                absolute: 0
            exclusion:
                groups: [participantList, participant]
        -
            rel: issues
            href:
                route: get_issues
                absolute: 0
            exclusion:
                groups: [participantList, participant]
    properties:
        project:
            expose: true
            groups: [projectList, project, participantList, participant]
        user:
            expose: true
            groups: [projectList, project, participantList, participant]
        role:
            expose: true
            groups: [projectList, project, participantList, participant]
