# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This implements the following type system shorthand:
#
#   type Query {
#     organization(id: ID!): Organization
#   }

Query:
    type: object
    config:
        description: "Kreta, modern project management solution"
        fields:
            organization:
                type: "Organization"
                args:
                    id:
                        description: "id of the organization"
                        type: "String!"
                resolve: "@=resolver('organization_id', [args])"
