# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
    kreta_web.listener_emptyProfileListener:
        class: Kreta\Bundle\WebBundle\EventListener\EmptyProfileListener
        arguments: [@security.context, @router, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kreta_web.listener_formHandlerFlashListener:
        class: Kreta\Bundle\WebBundle\EventListener\FormHandlerFlashListener
        arguments: [@session]
        tags:
            - { name: kernel.event_listener, event: kreta_web_event_form_handler, method: onFormHandlerEvent }

    #Form handlers
    kreta_web.form_handler_comment:
        class: Kreta\Bundle\WebBundle\FormHandler\CommentFormHandler
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher]

    kreta_web.form_handler_issue:
        class: Kreta\Bundle\WebBundle\FormHandler\IssueFormHandler
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher]

    kreta_web.form_handler_project:
        class: Kreta\Bundle\WebBundle\FormHandler\ProjectFormHandler
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher, @kreta_core.factory_media, @kreta_core.image_projects_uploader]

    #Events
    kreta_web.issue_events:
        class: Kreta\Bundle\WebBundle\NotifiableEvent\IssueEvents
        arguments: [@router]
        tags:
            - { name: kreta_notification.notifiable_event, label: issue }

    kreta_web.notifier_email:
        class: Kreta\Bundle\WebBundle\Notifier\EmailNotifier
        arguments: [@mailer]
        tags:
            - { name: kreta_notification.notifier, label: email }

    kreta_web.twig.issue_extension:
        class: Kreta\Bundle\WebBundle\Twig\IssueExtension
        tags:
            - { name: twig.extension }

    kreta_web.twig.notification_extension:
        class: Kreta\Bundle\WebBundle\Twig\NotificationExtension
        tags:
            - { name: twig.extension }
