# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_project.factory.label:
        class: %kreta_project.factory_label.class%
        arguments: [%kreta_project.label.class%]
    kreta_project.factory.participant:
        class: %kreta_project.factory_participant.class%
        arguments: [%kreta_project.participant.class%]
    kreta_project.factory.issue_priority:
        class: %kreta_project.factory_issue_priority.class%
        arguments: [%kreta_project.issue_priority.class%]
    kreta_project.factory.project:
        class: %kreta_project.factory_project.class%
        arguments:
            - %kreta_project.project.class%
            - @kreta_project.factory.participant
            - @kreta_workflow.factory.workflow
            - @kreta_media.factory.media
            - @kreta_project.uploader.image_project
