# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_project.event_listener.project_if_allowed_annotation:
        parent: kreta_core.event_listener.resource_if_allowed_annotation
        arguments:
            - '@kreta_project.repository.project'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onResourceIfAllowedAnnotationMethod }
