# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_project.subscriber.image_url:
        parent: kreta_media.subscriber.media_url.abstract
        arguments: [%kreta_project.project.class%, 'image']
        tags:
            - { name: jms_serializer.event_subscriber }
