# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.command_handler.sign_up_user:
        class: BenGorUser\User\Application\Command\SignUp\SignUpUserHandler
        arguments:
            - "@bengor_user.user.repository"
            - "@bengor_user.user.symfony_password_encoder"
            - "@bengor_user.user.factory_sign_up"
        tags:
            -
                name: bengor_user_user_command_bus_handler
                handles: BenGorUser\User\Application\Command\SignUp\SignUpUserCommand

    kreta.identity_access.command_handler.edit_profile:
        class: Kreta\IdentityAccess\Application\Command\EditProfileHandler
        arguments:
            - "@bengor_user.user.repository"
        tags:
            -
                name: bengor_user_user_command_bus_handler
                handles: Kreta\IdentityAccess\Application\Command\EditProfileCommand
