# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.user.infrastructure.persistence.user_repository:
        class: Kreta\IdentityAccess\Infrastructure\Persistence\Doctrine\ORM\User\DoctrineORMUserRepository
        factory: ["@doctrine.orm.default.entity_manager", getRepository]
        arguments:
            - Kreta\IdentityAccess\Domain\Model\User\User

    bengor_user.user.repository:
        alias: bengor.user.infrastructure.persistence.user_repository
