# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.query_handler.users_of_ids:
        class: Kreta\IdentityAccess\Application\Query\UsersOfIdsHandler
        arguments:
            - "@bengor_user.user.repository"
            - "@kreta.identity_access.data_transformer.public_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\IdentityAccess\Application\Query\UsersOfIdsQuery
