# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.invited_mailer_subscriber:
        class: BenGorUser\User\Domain\Event\UserInvitedMailerSubscriber
        arguments:
            - '@bengor_user.mailer.swift_mailer'
            - '@bengor_user.mailable_factory.invite'
            - '@bengor_user.symfony_url_generator'
            - bengor_user_user_sign_up
        tags:
            -
                name: bengor_user_user_event_subscriber
                subscribes_to: BenGorUser\User\Domain\Model\Event\UserInvited




    kreta.identity_access.simple_bus.serializer.native:
        class: Kreta\SharedKernel\Infrastructure\Serializer\SimpleBus\Serializer


    kreta.identity_access.command_handler.sign_up_by_invitation:
        class: BenGorUser\User\Application\Command\SignUp\ByInvitationSignUpUserHandler
        arguments:
            - "@bengor_user.user.repository"
            - "@bengor_user.user.symfony_password_encoder"
        tags:
            -
                name: command_handler
                handles: BenGorUser\User\Application\Command\SignUp\ByInvitationSignUpUserCommand
