# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.query_handler.count_task:
        class: Kreta\TaskManager\Application\Query\Project\Task\CountTasksHandler
        arguments:
            - "@kreta.task_manager.repository.project"
            - "@kreta.task_manager.specification_factory.project"
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.repository.task"
            - "@kreta.task_manager.specification_factory.task"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Project\Task\CountTasksQuery

    kreta.task_manager.query_handler.filter_tasks:
        class: Kreta\TaskManager\Application\Query\Project\Task\FilterTasksHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.specification_factory.organization"
            - "@kreta.task_manager.repository.project"
            - "@kreta.task_manager.specification_factory.project"
            - "@kreta.task_manager.repository.task"
            - "@kreta.task_manager.specification_factory.task"
            - "@kreta.task_manager.data_transformer.task_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Project\Task\FilterTasksQuery

    kreta.task_manager.query_handler.task_of_id:
        class: Kreta\TaskManager\Application\Query\Project\Task\TaskOfIdHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.repository.project"
            - "@kreta.task_manager.repository.task"
            - "@kreta.task_manager.data_transformer.task_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Project\Task\TaskOfIdQuery
