# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Mutation:
    type: object
    config:
        fields:
            createOrganization:
                builder: Mutation
                builderConfig:
                    inputType: CreateOrganizationInput
                    payloadType: CreateOrganizationPayload
                    mutateAndGetPayload: "@=mutation('create_organization', [args.offsetGet('input')])"
            createProject:
                builder: Mutation
                builderConfig:
                    inputType: CreateProjectInput
                    payloadType: CreateProjectPayload
                    mutateAndGetPayload: "@=mutation('create_project', [args.offsetGet('input')])"
