# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

TaskPriority:
    type: enum
    config:
        description: "One of the priorities in the Task priorities"
        values:
            LOW:
                value: "low"
                description: "Low priority."
            MEIDUM:
                value: "medium"
                description: "Medium priority."
            HIGH:
                value: "high"
                description: "High priority."
