# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Project\Model\IssuePriority:
    type: entity
    repositoryClass: Kreta\Component\Project\Repository\IssuePriorityRepository
    table: issue_priority
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 20
        color:
            type: string
            length: 8
    manyToOne:
        project:
            targetEntity: Kreta\Component\Project\Model\Interfaces\ProjectInterface
            inversedBy: issuePriorities
            joinColumn:
                name: project_id
                referencedColumnName: id
