# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

version: '2'

services:
    dbdata:
        image: busybox
        volumes:
            - /var/lib/mysql

    appdata:
        image: busybox
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - /var/www/symfony/IdentityAccess/var/logs
            - /var/www/symfony/TaskManager/var/logs
            - /vendor
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ~/.composer:/root/.composer
            - /tmpfs

    db:
        image: mysql
        ports:
            - 3306:3306
        volumes_from:
            - dbdata
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    rabbitmq:
        image: rabbitmq:3.6.5-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        environment:
            SYMFONY_ENV: ${SYMFONY_ENV}
        links:
            - db
            - redis
        volumes_from:
            - appdata

    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - appdata
            - nginx
