# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Media\Model\Media:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups:
                - userList
                - user
                - profile
                - projectList
                - project
                - issueList
                - issue
                - commentList
                - comment
                - participantList
                - participant
                - organizationList
                - organization
                - organizationParticipantList
                - organizationParticipant
        createdAt:
            expose: true
            groups: [userList, user, profile, project, organization]
        name:
            expose: true
            groups:
                - userList
                - user
                - profile
                - projectList
                - project
                - issueList
                - issue
                - commentList
                - comment
                - participantList
                - participant
                - organizationList
                - organization
                - organizationParticipantList
                - organizationParticipant
        updatedAt:
            expose: true
            groups: [userList, user, profile, project, organization]
