# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

certbot_auto_renew_user: "{{ security.deploy_user }}"
certbot_auto_renew_minute: 30
certbot_auto_renew_hour: 3
