# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

mysql_root_password: "{{ mysql.root_pass }}"
mysql_databases:
    -
        name: kreta_task_manager
        encoding: UTF8
    -
        name: kreta_identity_access
        encoding: UTF8
mysql_users:
    -
        name: kreta
        password: "{{ mysql.kreta_pass }}"
        priv: "*.*:ALL"

