# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

php_enablerepo: "remi-php71"
php_packages_state: "latest"
php_webserver_daemon: "nginx"
php_memory_limit: "1024M"
php_max_execution_time: "90"
php_upload_max_filesize: "20M"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
php_packages:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-fpm
    - php-gd
    - php-imap
    - php-ldap
    - php-mbstring
    - php-opcache
    - php-pdo
    - php-pear
    - php-pecl-apcu
    - php-xml
    - php-xmlrpc
    - php-bcmath
    - php-mysql
php_fpm_pool_user: "{{ security.deploy_user }}"
php_fpm_pool_group: "{{ security.deploy_user }}"
