# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Media\Model\Media:
    type: entity
    table: media
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        createdAt:
            column: created_at
            type: datetime
        name:
            type: string
            length: 255
        updatedAt:
            column: updated_At
            type: datetime
            nullable: true
