# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_organization.participant.class: Kreta\Component\Organization\Model\Participant
    kreta_organization.organization.class: Kreta\Component\Organization\Model\Organization

    kreta_organization.factory_participant.class: Kreta\Component\Organization\Factory\ParticipantFactory
    kreta_organization.factory_organization.class: Kreta\Component\Organization\Factory\OrganizationFactory

    kreta_organization.repository_participant.class: Kreta\Component\Organization\Repository\ParticipantRepository
    kreta_organization.repository_organization.class: Kreta\Component\Organization\Repository\OrganizationRepository

    kreta_organization.form_handler.organization.class: Kreta\Component\Organization\Form\Handler\OrganizationHandler

    kreta_organization.form_type.participant.class: Kreta\Component\Organization\Form\Type\ParticipantType
    kreta_organization.form_type.organization.class: Kreta\Component\Organization\Form\Type\OrganizationType
    kreta_organization.form_type.role.class: Kreta\Component\Organization\Form\Type\RoleType

    kreta_organization.security_organization_voter.class: Kreta\Bundle\OrganizationBundle\Security\Authorization\Voter\OrganizationVoter
