# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_organization.repository.participant:
        class: '%kreta_organization.repository_participant.class%'
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
        arguments:
            - '%kreta_organization.participant.class%'

    kreta_organization.repository.organization:
        class: '%kreta_organization.repository_organization.class%'
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
        arguments:
            - '%kreta_organization.organization.class%'
