# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

kreta_api_organization:
    type: rest
    resource: Kreta\Bundle\OrganizationBundle\Controller\OrganizationController

kreta_api_organization_participant:
    type: rest
    parent: kreta_api_organization
    resource: Kreta\Bundle\OrganizationBundle\Controller\ParticipantController
