# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Organization\Model\Organization:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'Name is already in use'
    properties:
        name:
            - NotBlank: ~
Kreta\Component\Organization\Model\Participant:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [user, organization]
            message: 'This participant is already exists in this organization'
    properties:
        role:
            - NotBlank: ~
        user:
            - NotBlank: ~
