# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Workflow\Model\Status:
    type: entity
    repositoryClass: Kreta\Component\Workflow\Repository\StatusRepository
    table: status
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        color:
            type: string
            length: 10
        name:
            type: string
            length: 100
        type:
            type: string
            length: 8
    manyToOne:
        workflow:
            targetEntity: Kreta\Component\Workflow\Model\Interfaces\WorkflowInterface
            inversedBy: statuses
            joinColumn:
                name: workflow_id
                referencedColumnName: id
                onDelete: CASCADE
    manyToMany:
        transitions:
            targetEntity: Kreta\Component\Workflow\Model\Interfaces\StatusTransitionInterface
            mappedBy: initialStates
            cascade: ['persist', 'remove']
