# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.graph_ql.mutation.create_project:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Project\CreateProjectMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.project"
        tags:
            - { name: overblog_graphql.mutation, alias: "create_project", method: "execute" }

    kreta.task_manager.graph_ql.mutation.edit_project:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Project\EditProjectMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.project"
        tags:
            - { name: overblog_graphql.mutation, alias: "edit_project", method: "execute" }
