# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.graph_ql.mutation.create_task:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Project\Task\CreateTaskMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.task_of_id"
        tags:
            - { name: overblog_graphql.mutation, alias: "create_task", method: "execute" }

    kreta.task_manager.graph_ql.mutation.edit_task:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Project\Task\EditTaskMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.task_of_id"
        tags:
            - { name: overblog_graphql.mutation, alias: "edit_task", method: "execute" }
    kreta.task_manager.graph_ql.mutation.change_task_progress:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Project\Task\ChangeTaskProgressMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.task_of_id"
        tags:
            - { name: overblog_graphql.mutation, alias: "change_task_progress", method: "execute" }
