# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

kreta_web_issue_new:
    path: /{projectShortName}/new
    defaults: { _controller: KretaWebBundle:Issue:new }

kreta_web_issue_view:
    path: /{projectShortName}-{issueNumber}
    defaults: { _controller: KretaWebBundle:Issue:view }

kreta_web_issue_edit:
    path: /{projectShortName}-{issueNumber}/edit
    defaults: { _controller: KretaWebBundle:Issue:edit }

kreta_web_issue_comment_new:
    path: /{projectShortName}-{issueNumber}/comment/new
    defaults: { _controller: KretaWebBundle:Issue:newComment }

kreta_web_issue_change_status:
    path: /{projectShortName}-{issueNumber}/status/{transitionId}
    defaults: { _controller: KretaWebBundle:Issue:editStatus }
