kreta_web_project_new:
    path:    /new
    defaults: { _controller: KretaWebBundle:Project:new }

kreta_web_project_edit:
    path:    /edit/{id}
    defaults: { _controller: KretaWebBundle:Project:edit }

kreta_web_project_view:
    path:     /{id}
    defaults: { _controller: KretaWebBundle:Project:view }

kreta_web_project_participant_new:
    path:     /{id}/participant
    methods:  [POST]
    defaults: { _controller: KretaWebBundle:Project:newParticipant }
