# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\User\Model\User:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_profile
                absolute: 0
            exclusion:
                groups: [profile]
        -
            rel: projects
            href:
                route: get_projects
                absolute: 0
            exclusion:
                groups: [profile]
    properties:
        createdAt:
            expose: true
            groups:
                - userList
                - user
                - profile
                - projectList
                - project
                - projectPrivate
                - organizationList
                - organization
                - organizationPrivate
        firstName:
            expose: true
            groups:
                - userList
                - user
                - profile
                - projectList
                - project
                - projectPrivate
                - issueList
                - issue
                - commentList
                - comment
                - participantList
                - participant
                - organizationList
                - organization
                - organizationPrivate
                - organizationParticipantList
                - organizationParticipant
        lastName:
            expose: true
            groups:
                - userList
                - user
                - profile
                - projectList
                - project
                - projectPrivate
                - issueList
                - issue
                - commentList
                - comment
                - participantList
                - participant
                - organizationList
                - organization
                - organizationPrivate
                - organizationParticipantList
                - organizationParticipant
        photo:
            expose: true
            groups:
                - userList
                - user
                - profile
                - projectList
                - project
                - projectPrivate
                - issueList
                - issue
                - commentList
                - comment
                - participantList
                - participant
                - organizationList
                - organization
                - organizationPrivate
                - organizationParticipantList
                - organizationParticipant
