# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\User\Model\User:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_profile
                absolute: true
            exclusion:
                groups: [profile]
        -
            rel: projects
            href:
                route: get_projects
                absolute: true
            exclusion:
                groups: [profile]
    properties:
        bitbucketAccessToken:
            expose: true
            groups: []
        bitbucketId:
            expose: true
            groups: [profile]
        createdAt:
            expose: true
            groups: [profile, projectList, project]
        firstName:
            expose: true
            groups: [profile, projectList, project, issueList, issue, commentList, comment, participantList, participant]
        githubAccessToken:
            expose: true
            groups: []
        githubId:
            expose: true
            groups: [profile]
        lastName:
            expose: true
            groups: [profile, projectList, project, issueList, issue, commentList, comment, participantList, participant]
        photo:
            expose: true
            groups: [profile, projectList, project, issueList, issue, commentList, comment, participantList, participant]
