-
    name: "Build hosts file"
    lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 {{ kreta.domains.identity_access }} {{ kreta.domains.task_manager }} {{ kreta.domains.composite_ui }}"
