# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

---
-
    name: create deployment user
    user:
        name: "{{ security.deploy_user }}"

-
    name: Retrieving all keys from GitHub
    shell: /usr/bin/curl https://github.com/{{ item }}.keys 2> /dev/null
    register: ssh_keys
    with_items: "{{ security.github_users_allowed }}"

-
    name: Set authorized key took from file
    authorized_key:
        user: "{{ security.deploy_user }}"
        state: present
        key: "{{ item.stdout }}"
    with_items: "{{ ssh_keys.results }}"
