# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Core\Model\Abstracts\AbstractModel:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [notificationList, notification, profile, workflowList, workflow, projectList, project, issueList, issue, labelList, label, commentList, comment, participantList, participant]

