# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_media.media.class: Kreta\Component\Media\Model\Media

    kreta_media.factory_media.class: Kreta\Component\Media\Factory\MediaFactory

    kreta_media.uploader_media.class: Kreta\Component\Media\Uploader\MediaUploader

    kreta_media.subscriber.media_url.abstract.class: Kreta\Bundle\MediaBundle\EventSubscriber\MediaUrlSubscriber
