# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# input EditTaskPayload {
#   task: Task
# }
EditTaskPayload:
    type: relay-mutation-payload
    config:
        fields:
            task:
                type: "Task"
