# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# input EditProjectPayload {
#   project: Project
# }
EditProjectPayload:
    type: relay-mutation-payload
    config:
        fields:
            project:
                type: "Project"
