# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This implements the following type system shorthand:
#
#   type OrganizationConnectionInput {
#     after: String,
#     first: Int,
#     before: String,
#     last: Int,
#     name: String
#   }
OrganizationConnectionInput:
    type: input-object
    config:
        fields:
            after:
                type: "String"
            first:
                type: "Int"
            before:
                type: "String"
            last:
                type: "Int"
            name:
                description: "name of the organization, it uses to filter the organizations. Typical 'q'"
                type: "String"
