# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.graph_ql.query_resolver.organization_of_id:
        class: Kreta\TaskManager\Infrastructure\Ui\Web\Api\GraphQL\Query\Organization\OrganizationOfIdResolver
        arguments:
            - "@kreta.task_manager.query_bus"
        tags:
            - { name: overblog_graphql.resolver, alias: "organization_id", method: "resolve" }
