# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.serialization.name_resolver:
        class: Kreta\IdentityAccess\Infrastructure\Serialization\NameResolver
        public: false

    kreta.identity_access.serialization.async_event_serializer:
        class: Kreta\SharedKernel\Serialization\AsyncEventSerializer
        public: false
        arguments:
            - "@kreta.identity_access.serialization.name_resolver"

    kreta.identity_access.serialization.simple_bus.async_event_serializer:
        class: Kreta\SharedKernel\Infrastructure\Serialization\SimpleBus\SimpleBusAsyncEventSerializer
        arguments:
            - "@kreta.identity_access.serialization.async_event_serializer"
