# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
    kreta_workflow.repository.workflow:
        class: %kreta_workflow.repository_workflow.class%
        factory: 
            - @doctrine.orm.entity_manager
            - getRepository
        arguments: 
            - %kreta_workflow.workflow.class%
    kreta_workflow.repository.status:
        class: %kreta_workflow.repository_status.class%
        factory: 
            - @doctrine.orm.entity_manager
            - getRepository
        arguments: 
            - %kreta_workflow.status.class%
    kreta_workflow.repository.status_transition:
        class: %kreta_workflow.repository_status_transition.class%
        factory: 
            - @doctrine.orm.entity_manager
            - getRepository
        arguments: 
            - %kreta_workflow.status_transition.class%
