# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

parameters:
    kreta_issue.issue.class: Kreta\Component\Issue\Model\Issue
    kreta_issue.resolution.class: Kreta\Component\Issue\Model\Resolution

    kreta_issue.factory_issue.class: Kreta\Component\Issue\Factory\IssueFactory
    kreta_issue.factory_resolution.class: Kreta\Component\Issue\Factory\ResolutionFactory

    kreta_issue.repository_issue.class: Kreta\Component\Issue\Repository\IssueRepository
    kreta_issue.repository_resolution.class: Kreta\Component\Issue\Repository\ResolutionRepository

    kreta_issue.form_issue_handler.class: Kreta\Bundle\IssueBundle\Form\Handler\IssueHandler

    kreta_issue.form_type.issue.class: Kreta\Bundle\IssueBundle\Form\Type\Api\IssueType

    kreta_issue.state_machine_issue.class: Kreta\Component\Issue\StateMachine\IssueStateMachine
    kreta_issue.security_issue_voter.class: Kreta\Bundle\IssueBundle\Security\Authorization\Voter\IssueVoter
