# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_issue.repository.issue:
        class: %kreta_issue.repository_issue.class%
        factory:
            - @doctrine.orm.entity_manager
            - getRepository
        arguments:
            - %kreta_issue.issue.class%
    kreta_issue.repository.resolution:
        class: %kreta_issue.repository_resolution.class%
        factory:
            - @doctrine.orm.entity_manager
            - getRepository
        arguments:
            - %kreta_issue.resolution.class%
