# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### HANDLERS ####
    kreta_user.form_handler.invitation:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\User\Form\Type\InvitationType

    kreta_user.form_handler.profile:
        class: %kreta_user.form_user_handler.class%
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\User\Form\Type\ProfileType
            - '@kreta_media.factory.media'
            - '@kreta_user.uploader.image_user'

    kreta_user.form_handler.registration:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\User\Form\Type\RegistrationType

#### TYPES ####
    kreta_user.form_type.invitation:
        class: %kreta_user.form_type.invitation.class%
        arguments:
            - %kreta_user.user.class%
            - '@kreta_user.factory.user'
            - '@security.token_storage'
            - null
            - [invitation]
        tags:
            - { name: form.type }

    kreta_user.form_type.profile:
        class: %kreta_user.form_type.profile.class%
        arguments:
            - %kreta_user.user.class%
            - '@kreta_user.factory.user'
            - '@security.token_storage'
            - null
            - [profile]
        tags:
            - { name: form.type }

    kreta_user.form_type.registration:
        class: %kreta_user.form_type.registration.class%
        arguments:
            - %kreta_user.user.class%
            - '@kreta_user.factory.user'
            - null
            - null
            - [registration]
        tags:
            - { name: form.type }

