# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
#### HANDLERS ####
    kreta_user.form_handler.user:
        class: %kreta_user.form_user_handler.class%
        parent: kreta_core.form_handler.handler
        arguments: 
            - kreta_user_user_type
            - @kreta_media.factory.media
            - @kreta_user.uploader.image_user

#### TYPES ####
    kreta_user.form_type.user:
        class: %kreta_user.form_type.user.class%
        arguments:
            - %kreta_user.user.class%
            - @kreta_user.factory.user
        tags:
            - { name: form.type, alias: 'kreta_user_user_type' }
