# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_user.event_listener.authentication_listener:
        class: Kreta\Bundle\UserBundle\EventListener\AuthenticationListener
        arguments:
            - @fos_oauth_server.client_manager.default
            - @fos_oauth_server.server
            - %oauth.web.client_secret%
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_listener, event: kreta_user_event_authorization, method: onAuthorizationEvent }
            - { name: kernel.event_listener, event: kreta_user_event_cookie, method: onCookieEvent }
            - { name: kernel.event_listener, event: fos_user.registration.success, method: onRegistrationSuccess }
