# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_user.uploader.image_user:
        class: %kreta_media.uploader_media.class%
        arguments:
            - '@kreta_user.uploader_filesystem.image_user'
    kreta_user.uploader_filesystem.image_user:
        class: Gaufrette\Filesystem
        factory:
            - '@knp_gaufrette.filesystem_map'
            - get
        arguments:
            - %users.image.uploader.filesystem%
