# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\User\Model\User:
    properties:
        firstName:
            - NotBlank: { groups: [profile, invitation] }
        lastName:
            - NotBlank: { groups: [profile, invitation] }
    getters:
        enabled:
            - 'IsFalse':
                message: 'This user is already an enabled kreta user'
                groups: [invitation]

FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'This email is already invited'
            groups: [invitation]
    properties:
        email:
            - Email:
                checkMX: true
                checkHost: true
            - NotBlank: ~
        username:
            - NotBlank: { groups: [profile, invitation] }
        plainPassword:
            - NotBlank: { groups: [registration] }
            - Length: { min: 6, groups: [registration] }
