# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### FORMS ####
    kreta_notification.form_handler.notification:
        parent: kreta_core.form_handler.handler
        arguments:
            - kreta_notification_notification_type

#### TYPES ####
    kreta_notification.form_type.notifcation:
        class: %kreta_notification.form_type.notification.class%
        arguments:
            - %kreta_notification.notification.class%
            - @kreta_notification.factory.notification
            - @security.token_storage
        tags:
            - { name: form.type }
