# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_notification.notifier_registry:
        class: %kreta_notification.notifier_registry.class%

    kreta_notification.notifier.email:
        class: Kreta\Component\Notification\Notifier\EmailNotifier
        arguments: [@mailer]
        tags:
            - { name: kreta_notification.notifier, label: email }
