# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.php_amqp_lib.user_registered:
        class: Kreta\SharedKernel\Infrastructure\Messaging\AMQP\PhpAmqpLib\Consumer
        public: false
        arguments:
            - "@kreta.task_manager.event_subscriber.user_registered"
            - "identity_access.user_register"

    kreta.task_manager.rabbit_mq_bundle.user_registered:
        class: Kreta\SharedKernel\Infrastructure\Messaging\AMQP\RabbitMqBundle\Consumer
        arguments:
            - "@kreta.task_manager.php_amqp_lib.user_registered"
