# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.command.fixtures_organization:
        class: Kreta\TaskManager\Infrastructure\Ui\Cli\Symfony\Command\OrganizationFixturesCommand
        tags:
            - { name: console.command }

    kreta.task_manager.command.fixtures_project:
        class: Kreta\TaskManager\Infrastructure\Ui\Cli\Symfony\Command\ProjectFixturesCommand
        tags:
            - { name: console.command }

    kreta.task_manager.command.fixtures_user:
        class: Kreta\TaskManager\Infrastructure\Ui\Cli\Symfony\Command\UserFixturesCommand
        tags:
            - { name: console.command }
