# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.event_subscriber.organization_created:
        class: Kreta\TaskManager\Domain\Event\Organization\OrganizationCreatedSubscriber
        tags:
            -
                name: event_subscriber
                subscribes_to: Kreta\TaskManager\Domain\Model\Organization\OrganizationCreated
                method: handle
