# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Issue\Model\Resolution:
    type: entity
    repositoryClass: Kreta\Component\Issue\Repository\ResolutionRepository
    table: resolution
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        description:
            type: text
