# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\User\Model\User:
    type: entity
    repositoryClass: Kreta\Component\User\Repository\UserRepository
    table: user
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        createdAt:
            column: created_at
            type: datetime
        firstName:
            column: first_name
            type: string
            length: 100
            nullable: true
        lastName:
            column: last_name
            type: string
            length: 100
            nullable: true
    oneToOne:
        photo:
            targetEntity: Kreta\Component\Media\Model\Interfaces\MediaInterface
            joinColumn:
                name: photo
                referencedColumnName: id
            cascade: ['persist', 'remove']
